import 'package:go_router/go_router.dart';

import 'routes.dart';

/// Central GoRouter instance.
///
/// Feature jobs (J4–J13) do NOT edit this file. Instead they append their
/// `RouteBase` entries to [appRoutes] (exported from `routes.dart`),
/// which is referenced here. Keeps GoRouter centralization without edits.
final GoRouter appRouter = GoRouter(
  initialLocation: Routes.splash,
  routes: <RouteBase>[...appRoutes],
);
